"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RecoilRoot } from "recoil";
import * as S from "./_component/global.styles";
import SearchNav from "./_component/SearchNav/SearchNav";
import { QueryClient, QueryClientProvider } from "react-query";
import GlobalStyle from "@/styles/global";
import { Children } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRoot>
          <QueryClientProvider client={queryClient}>
            <GlobalStyle />
            <S.Container>
              <RecoilRoot>
                <S.NavContainer>
                  <SearchNav />
                  {children}
                </S.NavContainer>
              </RecoilRoot>
            </S.Container>
          </QueryClientProvider>
        </RecoilRoot>
      </body>
    </html>
  );
}
